export const BASE_URL = 'https://api.instore-experience.com/2017/01/REST'
export const LOGIN_URL = BASE_URL + '/token'
export const USER_CONTENTS_URL = BASE_URL + '/Content/Root/Users/'
export const USER_PLAYLISTS_URL = BASE_URL + '/Playlists/Dynamic/'
export const DEVICES_URL = BASE_URL + '/Devices'
